name: 'My WorkFlows"
description: 'Ngetes Pembuatan Workflow'
inputs:
  nama:
    default: 'Haloo ini testing'
    description: 'Fungsi Ini Testing'
    
runs:
  using: "composite"
  steps:
    - name: Memanggil Fungsi
      run: echo ${{inputs.nama}}
