name: 'Kivy App to APK'
description: 'Convert Kivy app to APK'
inputs:
  python-version:
    description: 'Python version to use'
    default: '3.8'
  workdir:
    default: '.'
    description: 'Working directory'
  buildozer-cmd:
    default: 'buildozer android debug'
    description: 'Buildozer command to use'
    